Python3 Support For Maya2022/Maya2023
Ray1235/CoDMayaTools pull request #19
Opened 2022-04-29 07:25 UTC by JTAG7371

This adds support for Maya 2022 and Maya 2023

Python3 support.

2022-06-19 05:25 UTC, ribbitpoison requested changes
This happens when trying to import a notetrack.

![image](https://user-images.githubusercontent.com/95391751/174467180-83f75e16-f3d2-4e9f-bbbf-05d084a0c38f.png)
You might want to fix that.

2022-06-19 22:09 UTC, JTAG7371 commented
> This happens when trying to import a notetrack.
> 
> ![image](https://user-images.githubusercontent.com/95391751/174467180-83f75e16-f3d2-4e9f-bbbf-05d084a0c38f.png) You might want to fix that.

Can you give me an example file that you are using that reports this error so i can take a look

2022-06-19 22:16 UTC, ribbitpoison commented
> > This happens when trying to import a notetrack.
> > ![image](https://user-images.githubusercontent.com/95391751/174467180-83f75e16-f3d2-4e9f-bbbf-05d084a0c38f.png) You might want to fix that.
> 
> Can you give me an example file that you are using that reports this error so i can take a look
[vm_zom_raygun_mk3_dw_first_raise.zip](https://github.com/LunaRyuko/CoDMayaTools/files/8936494/vm_zom_raygun_mk3_dw_first_raise.zip)

Here's the animation in question. This is a SEAnim of the Ray Gun MK3..

2022-06-24 04:07 UTC, xCortlandx commented
for note, frames in notetracks.iteritems():

to

for note, frames in notetracks.items():

2022-06-24 06:13 UTC, JTAG7371 commented
Fixed and committed. Feel free to test.

2026-05-04 04:24 UTC, closed without merging